// @generated by protoc-gen-connect-es v1.5.0
// @generated from file grpcoauth/v1/oauth.proto (package grpcoauth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CallbackRequest, GetAuthorizeCodeRequest, GetAuthorizeCodeResponse, GetTokenRequest, GetTokenResponse } from "./oauth_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service grpcoauth.v1.Oauth2Service
 */
export declare const Oauth2Service: {
  readonly typeName: "grpcoauth.v1.Oauth2Service",
  readonly methods: {
    /**
     * @generated from rpc grpcoauth.v1.Oauth2Service.GetAuthorizeCode
     */
    readonly getAuthorizeCode: {
      readonly name: "GetAuthorizeCode",
      readonly I: typeof GetAuthorizeCodeRequest,
      readonly O: typeof GetAuthorizeCodeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grpcoauth.v1.Oauth2Service.GetToken
     */
    readonly getToken: {
      readonly name: "GetToken",
      readonly I: typeof GetTokenRequest,
      readonly O: typeof GetTokenResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service grpcoauth.v1.OauthCallbackService
 */
export declare const OauthCallbackService: {
  readonly typeName: "grpcoauth.v1.OauthCallbackService",
  readonly methods: {
    /**
     * @generated from rpc grpcoauth.v1.OauthCallbackService.Callback
     */
    readonly callback: {
      readonly name: "Callback",
      readonly I: typeof CallbackRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

