// @generated by protoc-gen-connect-es v1.5.0
// @generated from file grpcoauth/v1/user.proto (package grpcoauth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { GetAccessTokenInfoResponse, GetUserMeResponse, UserLogoutResponse } from "./user_pb.js";

/**
 * @generated from service grpcoauth.v1.UserService
 */
export declare const UserService: {
  readonly typeName: "grpcoauth.v1.UserService",
  readonly methods: {
    /**
     * @generated from rpc grpcoauth.v1.UserService.GetAccessTokenInfo
     */
    readonly getAccessTokenInfo: {
      readonly name: "GetAccessTokenInfo",
      readonly I: typeof Empty,
      readonly O: typeof GetAccessTokenInfoResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grpcoauth.v1.UserService.GetUserMe
     */
    readonly getUserMe: {
      readonly name: "GetUserMe",
      readonly I: typeof Empty,
      readonly O: typeof GetUserMeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grpcoauth.v1.UserService.UserLogout
     */
    readonly userLogout: {
      readonly name: "UserLogout",
      readonly I: typeof Empty,
      readonly O: typeof UserLogoutResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

