name: push-grpc-go

on:
  push:
    tags:
      - '*'
jobs:
  install-buf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS 20.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: |
          npm install @bufbuild/protobuf @bufbuild/protoc-gen-es @bufbuild/buf

  install-python:
    runs-on: ubuntu-latest
    steps:
      - name: setUp python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: install dependencies
        run: |
          python -m pip install --updgrade pip
          python -m pip install grpclib protobuf

  generate-buf:
    runs-on: ubuntu-latest
    steps:
      - name: generate buf
        run: |
          npx buf dep update
          npx buf generate
          

  ts:
    needs: [install-buf, install-python, generate-buf]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout assistant_proto code
        uses: actions/checkout@v4
      - name: Add remote-url
        env:
          TOKEN: ${{secrets.Secret}}
        run: |
          rm -rf ./grpc-oauth-ts
          git clone https://user:$TOKEN@github.com/vet1ments/grpc-oauth-ts
          cd grpc-oauth-ts
          git config user.name "vet1ments"
          git config user.email "vet1ments@naver.com"

          cp  -r ../ts/* ./ 
          git add .
          git commit -m "${{ steps.tag.outputs.TAG_NAME }} update"
          git push origin master
          git tag ${{ steps.tag.outputs.TAG_NAME }}
          git push origin ${{ steps.tag.outputs.TAG_NAME }}
          git config --unset user.name "vet1ments"
          git config --unset user.email "vet1ments@naver.com"
          rm -rf ./grpc-oauth-ts
  go:
    needs: [install-buf, install-python, generate-buf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout assistant_proto code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Add remote-url
        env:
          TOKEN: ${{secrets.Secret}}
        run: |
          rm -rf ./grpc-oauth-go
          git clone https://user:$TOKEN@github.com/vet1ments/grpc-oauth-go
          cd grpc-oauth-go
          git config user.name "vet1ments"
          git config user.email "vet1ments@naver.com"
          
          cp -r ../go/grpcoauth/* ./ 
          rm go.mod
          rm go.sum
          
          go mod init github.com/vet1ments/grpc-oauth-go
          go mod tidy
          
          
          git add .
          git commit -m "${{ steps.tag.outputs.TAG_NAME }} update"
          git push origin master
          git tag ${{ steps.tag.outputs.TAG_NAME }}
          git push origin ${{ steps.tag.outputs.TAG_NAME }}
          git config --unset user.name "vet1ments"
          git config --unset user.email "vet1ments@naver.com"
          rm -rf ./grpc-oauth-go
          
