name: push-grpc-go

on:
  push:
    tags:
      - '*'
jobs:
  install-buf:
    runs-on: ubuntu-latest
    steps:
      - name: setUp python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install grpclib protobuf
      - name: Checkout assistant_proto code
        uses: actions/checkout@v4
      - name: Set up NodeJS 20.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: |
          npm install --save-dev @bufbuild/buf @connectrpc/protoc-gen-connect-es@"^1.0.0" @bufbuild/protoc-gen-es@"^1.0.0"
          npm install @connectrpc/connect@"^1.0.0" @connectrpc/connect-web@"^1.0.0" @bufbuild/protobuf@"^1.0.0"
          npx buf --version
          npm install

      - name: dep update
        run: |
          npx buf dep update
          npx buf generate --include-imports

      - name: git config
        run: |
          git config --global user.name "vet1ments"
          git config --global user.email "vet1ments@naver.com"

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: update ts
        env:
          TOKEN: ${{secrets.Secret}}
        run: |
          rm -rf ./grpc-oauth-ts
          git clone https://user:$TOKEN@github.com/vet1ments/grpc-oauth-ts
          rm -r ./grpc-oauth-ts/*
          cd grpc-oauth-ts
          cp  -r ../ts/* ./
          git add .
          git commit -m "${{ steps.tag.outputs.TAG_NAME }} update"
          git push origin master
          git tag ${{ steps.tag.outputs.TAG_NAME }}
          git push origin ${{ steps.tag.outputs.TAG_NAME }}
          cd ..
          rm -rf ./grpc-oauth-ts

      - name: update go
        env:
          TOKEN: ${{secrets.Secret}}
        run: |
          rm -rf ./grpc-oauth-go
          git clone https://user:$TOKEN@github.com/vet1ments/grpc-oauth-go
          rm -r ./grpc-oauth-go/*
          cd grpc-oauth-go

          cp -r ../go/grpcoauth/* ./ 

          go mod init github.com/vet1ments/grpc-oauth-go
          go mod tidy


          git add .
          git commit -m "${{ steps.tag.outputs.TAG_NAME }} update"
          git push origin master
          git tag ${{ steps.tag.outputs.TAG_NAME }}
          git push origin ${{ steps.tag.outputs.TAG_NAME }}
          rm -rf ./grpc-oauth-go

      - name: update py
        env:
          TOKEN: ${{secrets.Secret}}
        run: |
          rm -rf ./grpc-oauth-python
          git clone https://user:$TOKEN@github.com/vet1ments/grpc-oauth-python
          rm -r ./grpc-oauth-python/*
          cd grpc-oauth-python
          cp -r ../python/grpcoauth/* ./
          
          git add .
          git commit -m "${{ steps.tag.outputs.TAG_NAME }} update"
          git push origin master
          git tag ${{ steps.tag.outputs.TAG_NAME }}
          git push origin ${{ steps.tag.outputs.TAG_NAME }}
          rm -rf ./grpc-oauth-python
